name: Test AWS OIDC

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  test-aws-oidc:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-west-1

      - name: Who am I?
        run: |
          aws sts get-caller-identity